/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Outros;

import Controle.ControleFuncionario;
import Controle.ControleObjeto;
import Modelo.BEAN.Fornecimento;
import Modelo.BEAN.Funcionario;
import Modelo.BEAN.Objeto;
import Modelo.BEAN.ObjetoFornecimento;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilherme
 */
public class FRMFornecimento extends javax.swing.JFrame {

    private List<Objeto> mercadoriasListadas;
    private Objeto mercadoriaSelecionada;
    private List<ObjetoFornecimento> mercadoriasNoFornecimento;
    private Fornecimento fornecimento;

    /**
     * Creates new form FRMFornecimento
     */
    public FRMFornecimento() {
        initComponents();

        fornecimento = new Fornecimento();
        mercadoriaSelecionada = null;
        mercadoriasNoFornecimento = new ArrayList<>();
        try {
            mercadoriasListadas = ControleObjeto.listarTodosMercadoriasEAtivos();
            this.preencheTabelaPesquisa();
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, "Deu ruium: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbOpc = new javax.swing.JComboBox<>();
        tfDado = new javax.swing.JTextField();
        btnLocalizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePesquisa = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfPreco = new javax.swing.JTextField();
        tfQuant = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnInserirItem = new javax.swing.JButton();
        cbAlterar = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        lblQtdEstoque = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfLote = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnRemover = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMercadoriasInseridas = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Localizar mercadoria por:");

        cbOpc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listar todos", "Código", "Nome", "(A partir) Preço de compra", "(Até)Preço de compra", "Listar apenas ativos", "Listar apenas inativos" }));
        cbOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpcActionPerformed(evt);
            }
        });

        tfDado.setForeground(new java.awt.Color(153, 153, 153));
        tfDado.setText("Insira o dado para pesquisa...");
        tfDado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDadoFocusLost(evt);
            }
        });
        tfDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDadoActionPerformed(evt);
            }
        });
        tfDado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDadoKeyTyped(evt);
            }
        });

        btnLocalizar.setText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(cbOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfDado, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLocalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnLocalizar))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Escolha a mercadoria"));

        tablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablePesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePesquisaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePesquisa);

        jLabel6.setText("Código:");

        jLabel13.setText("Nome:");

        jLabel14.setText("Preço de compra:");

        tfPreco.setEnabled(false);
        tfPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPrecoFocusGained(evt);
            }
        });
        tfPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecoActionPerformed(evt);
            }
        });
        tfPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrecoKeyTyped(evt);
            }
        });

        tfQuant.setForeground(new java.awt.Color(153, 153, 153));
        tfQuant.setText("Insira a quantidade...");
        tfQuant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfQuantFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfQuantFocusLost(evt);
            }
        });
        tfQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantActionPerformed(evt);
            }
        });
        tfQuant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQuantKeyTyped(evt);
            }
        });

        jLabel2.setText("Quantidade fornecida:");

        btnInserirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/addProduto.png"))); // NOI18N
        btnInserirItem.setText("Inserir");
        btnInserirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirItemActionPerformed(evt);
            }
        });
        btnInserirItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnInserirItemKeyTyped(evt);
            }
        });

        cbAlterar.setBackground(new java.awt.Color(204, 255, 204));
        cbAlterar.setText("Alterar neste fornecimento");
        cbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlterarActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade em estoque:");

        jLabel5.setText("Lote:");

        tfLote.setForeground(new java.awt.Color(153, 153, 153));
        tfLote.setText("Insira o lote...");
        tfLote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfLoteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLoteFocusLost(evt);
            }
        });
        tfLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbAlterar)
                        .addContainerGap(10, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)
                        .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblQtdEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInserirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfLote))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel13))
                            .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQtdEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAlterar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserirItem)
                        .addGap(72, 72, 72))))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/TiraProduto.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/FinalVenda.png"))); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/logout.png"))); // NOI18N
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizar)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Mercadorias já selecionadas"));

        tableMercadoriasInseridas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableMercadoriasInseridas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpcActionPerformed
        if (cbOpc.getSelectedIndex() == 0) {
            try {
                mercadoriasListadas = ControleObjeto.listarTodosMercadorias();
                this.preencheTabelaPesquisa();
                this.verificaTabelaPesquisa();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
            }
        } else if (cbOpc.getSelectedIndex() == 5){
            try {
                mercadoriasListadas = ControleObjeto.listarTodosMercadoriasEAtivos();
                this.preencheTabelaPesquisa();
                this.verificaTabelaPesquisa();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
            }
        }else if (cbOpc.getSelectedIndex() == 6){
            try {
                mercadoriasListadas = ControleObjeto.listarTodosMercadoriasEInativos();
                this.preencheTabelaPesquisa();
                this.verificaTabelaPesquisa();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
            }
        }
    }//GEN-LAST:event_cbOpcActionPerformed

    private void tfDadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDadoFocusGained
        if (tfDado.getText().equals("Insira o dado para pesquisa...")) {
            tfDado.setText("");
            tfDado.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfDadoFocusGained

    private void tfDadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDadoFocusLost
        if (tfDado.getText().equals("")) {
            tfDado.setForeground(Color.GRAY);
            tfDado.setText("Insira o dado para pesquisa...");
        }
    }//GEN-LAST:event_tfDadoFocusLost

    private void tfDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDadoActionPerformed
        this.localizar();
    }//GEN-LAST:event_tfDadoActionPerformed

    private void tfDadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDadoKeyTyped

    }//GEN-LAST:event_tfDadoKeyTyped

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        this.localizar();
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void tablePesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePesquisaMouseClicked
        int qnt = tablePesquisa.getSelectedColumnCount();

        if (qnt < 1) {

        } else if (qnt > 1) {

        } else {
            mercadoriaSelecionada = mercadoriasListadas.get(tablePesquisa.getSelectedRow());
            this.preencheDados();
        }
    }//GEN-LAST:event_tablePesquisaMouseClicked

    private void tfPrecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrecoFocusGained
        tfPreco.selectAll();
    }//GEN-LAST:event_tfPrecoFocusGained

    private void tfPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecoActionPerformed
        tfLote.requestFocusInWindow();
    }//GEN-LAST:event_tfPrecoActionPerformed

    private void tfPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecoKeyTyped
        String caracteres = "0987654321.,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfPrecoKeyTyped

    private void tfQuantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfQuantFocusGained
        if (tfQuant.getText().equals("Insira a quantidade...")) {
            tfQuant.setText("");
            tfQuant.setForeground(Color.BLACK);
        } else {
            tfQuant.selectAll();
        }
    }//GEN-LAST:event_tfQuantFocusGained

    private void tfQuantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfQuantFocusLost
        if (tfQuant.getText().equals("")) {
            tfQuant.setText("Insira a quantidade...");
            tfQuant.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfQuantFocusLost

    private void tfQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantActionPerformed
        this.inserirItem();
    }//GEN-LAST:event_tfQuantActionPerformed

    private void tfQuantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantKeyTyped
        String caracteres = "0987654321.,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfQuantKeyTyped

    private void btnInserirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirItemActionPerformed
        this.inserirItem();
    }//GEN-LAST:event_btnInserirItemActionPerformed

    private void btnInserirItemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInserirItemKeyTyped

    }//GEN-LAST:event_btnInserirItemKeyTyped

    private void cbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlterarActionPerformed
        tfPreco.setEnabled(cbAlterar.isSelected());

        if (mercadoriaSelecionada != null) {
            if (!cbAlterar.isSelected()) {
                tfPreco.setText(mercadoriaSelecionada.getPrecoCompraBase() + "");
            }
        }
    }//GEN-LAST:event_cbAlterarActionPerformed

    private void tfLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoteActionPerformed
        tfQuant.requestFocusInWindow();
    }//GEN-LAST:event_tfLoteActionPerformed

    private void tfLoteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLoteFocusGained
        if (tfLote.getText().equals("Insira o lote...")) {
            tfLote.setText("");
            tfLote.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfLoteFocusGained

    private void tfLoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLoteFocusLost
        if (tfLote.getText().equals("")) {
            tfLote.setText("Insira o lote...");
            tfLote.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfLoteFocusLost

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int qnt = tableMercadoriasInseridas.getSelectedRowCount();

        if (qnt < 1) {
            JOptionPane.showMessageDialog(null, "Selecione um ítem da lista ao lado para remover.");
        } else if (qnt > 1) {
            JOptionPane.showMessageDialog(null, "Apenas um ítem da lista deve ser selecionado por vez.");
        } else {
            ObjetoFornecimento of = mercadoriasNoFornecimento.get(tableMercadoriasInseridas.getSelectedRow());
            mercadoriasNoFornecimento.remove(of);
            this.preencheTabelaMercadoriasInseridas();
            this.calculaTotal();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        if (mercadoriasNoFornecimento.size() == 0) {
            JOptionPane.showMessageDialog(null, "Insira ao menos um item.");
        } else {

            Funcionario f = new Funcionario();
            f.setCodigo(2);
            ControleFuncionario.setFuncionarioLogado(f);

            FRMFinalizarFornecimento fim = new FRMFinalizarFornecimento();

            fornecimento.setObjetosNoFornecimento(mercadoriasNoFornecimento);

            fim.pegaFornecimento(fornecimento);

            fim.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMFornecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMFornecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMFornecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMFornecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMFornecimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnInserirItem;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JCheckBox cbAlterar;
    private javax.swing.JComboBox<String> cbOpc;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQtdEstoque;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tableMercadoriasInseridas;
    private javax.swing.JTable tablePesquisa;
    private javax.swing.JTextField tfDado;
    private javax.swing.JTextField tfLote;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfQuant;
    // End of variables declaration//GEN-END:variables

    private void localizar() {
        if ((tfDado.getText().equals("")) || (tfDado.getText().equals("Insira o dado para pesquisa..."))) {
            JOptionPane.showMessageDialog(null, "Insira algum dado para pesquisa.");
        } else {
            if (cbOpc.getSelectedIndex() == 1) {
                try {
                    mercadoriasListadas = ControleObjeto.listarMercadoriaPorCodigo(Integer.parseInt(tfDado.getText()));
                    this.preencheTabelaPesquisa();
                    this.verificaTabelaPesquisa();
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Atenção: para pesquisa por código, insira apenas números.");
                } catch (RuntimeException e) {
                    JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
                }

            } else if (cbOpc.getSelectedIndex() == 2) {
                try {
                    mercadoriasListadas = ControleObjeto.listarMercadoriaPorNome(tfDado.getText());
                    this.preencheTabelaPesquisa();
                    this.verificaTabelaPesquisa();
                } catch (RuntimeException e) {
                    JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
                }
            } else if (cbOpc.getSelectedIndex() == 3) {
                String texto = tfDado.getText();

                if (texto.contains(",")) {
                    String partes[] = texto.split(",");
                    String parte1 = partes[0];
                    String parte2 = partes[1];
                    texto = parte1 + "." + parte2;
                }
                try {
                    mercadoriasListadas = ControleObjeto.listarMercadoriaPorValorCompraMenor(Float.parseFloat(texto));
                    this.preencheTabelaPesquisa();
                    this.verificaTabelaPesquisa();
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Atenção: para pesquisa por valores, insira apenas números.");
                } catch (RuntimeException e) {
                    JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
                }

            } else if (cbOpc.getSelectedIndex() == 4) {
                String texto = tfDado.getText();

                if (texto.contains(",")) {
                    String partes[] = texto.split(",");
                    String parte1 = partes[0];
                    String parte2 = partes[1];
                    texto = parte1 + "." + parte2;
                }
                try {
                    mercadoriasListadas = ControleObjeto.listarMercadoriaPorValorCompraMaior(Float.parseFloat(texto));
                    this.preencheTabelaPesquisa();
                    this.verificaTabelaPesquisa();
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Atenção: para pesquisa por valores, insira apenas números.");
                } catch (RuntimeException e) {
                    JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
                }
            }
        }
    }

    private void preencheTabelaPesquisa() {
        DefaultTableModel dtm = this.criaTabelaPesquisa();

        dtm.addColumn("Código");
        dtm.addColumn("Nome");
        dtm.addColumn("Preço de compra");
        dtm.addColumn("Qtde em estoque");

        for (Objeto ml : mercadoriasListadas) {
            dtm.addRow(new Object[]{ml.getCodigo(), ml.getNome(), ml.getPrecoCompraBase(), ml.getQtdeEstoque()});
        }

        tablePesquisa.setModel(dtm);

    }

    private DefaultTableModel criaTabelaPesquisa() {
        DefaultTableModel dTable = new DefaultTableModel() {
            //Define o tipo dos campos (coluna) na mesma ordem que as colunas foram criadas
            Class[] types = new Class[]{
                java.lang.Integer.class, //codigo
                java.lang.String.class, //nome
                java.lang.Float.class, //preço de compra
                java.lang.Float.class //Qtde em estoque
            };

            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;

        };
        
    return dTable;
    }

    private void verificaTabelaPesquisa() {
        if (tablePesquisa.getRowCount() == 1) {
            mercadoriaSelecionada = mercadoriasListadas.get(0);
            this.preencheDados();
        }
    }

    private void preencheDados() {
        lblCodigo.setText(mercadoriaSelecionada.getCodigo() + "");
        lblNome.setText(mercadoriaSelecionada.getNome());
        lblQtdEstoque.setText(mercadoriaSelecionada.getQtdeEstoque() + "");
        tfPreco.setText(mercadoriaSelecionada.getPrecoCompraBase() + "");
        tfQuant.setForeground(Color.BLACK);
        tfQuant.setText("1");
        tfLote.setText("");
        tfLote.setForeground(Color.BLACK);
        tfLote.requestFocusInWindow();
    }

    private void inserirItem() {
        if (mercadoriaSelecionada == null) {
            JOptionPane.showMessageDialog(null, "Selecione uma mercadoria ao lado.");
        } else {
            if (tfPreco.getText().equals("") || (tfQuant.getText().equals("Insira a quantidade..."))
                    || (tfQuant.getText().equals("")) || (tfLote.getText().equals("")) || (tfLote.getText().equals("Insira o lote..."))) {
                JOptionPane.showMessageDialog(null, "Todos os dados devem ser preenchidos");
            } else {

                ObjetoFornecimento of = new ObjetoFornecimento();

                of.setObjeto(mercadoriaSelecionada);
                of.setFornecimento(fornecimento);

                String qtde = tfQuant.getText();

                if (qtde.contains(",")) {
                    String[] parts = qtde.split(",");
                    String part1 = parts[0];
                    String part2 = parts[1];
                    qtde = part1 + "." + part2;
                }

                of.setQtdeFornecida(Float.parseFloat(qtde));

                String precoPraticado = tfPreco.getText();

                if (precoPraticado.contains(",")) {
                    String[] parts = precoPraticado.split(",");
                    String part1 = parts[0];
                    String part2 = parts[1];
                    precoPraticado = part1 + "." + part2;
                }

                of.setPrecoPraticadoCompra(Float.parseFloat(precoPraticado));

                if (!this.itemJaInserido(of)) {
                    mercadoriasNoFornecimento.add(of);
                    this.preencheTabelaMercadoriasInseridas();
                } else {
                    Object[] opcoes = {"Substituir", "Acrescentar quantidade", "Cancelar"};
                    int opc = JOptionPane.showOptionDialog(null, "Mercadoria já inserida! O que deseja fazer?",
                            "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opcoes, opcoes[0]);

                    if (opc == 0) {
                        for (ObjetoFornecimento m : mercadoriasNoFornecimento) {
                            if (m.getObjeto().getCodigo() == of.getObjeto().getCodigo()) {
                                m.setPrecoPraticadoCompra(of.getPrecoPraticadoCompra());
                                m.setQtdeFornecida(of.getQtdeFornecida());
                                this.preencheTabelaMercadoriasInseridas();
                            }
                        }
                    } else if (opc == 1) {
                        for (ObjetoFornecimento m : mercadoriasNoFornecimento) {
                            if (m.getObjeto().getCodigo() == of.getObjeto().getCodigo()) {
                                m.setQtdeFornecida(m.getQtdeFornecida() + of.getQtdeFornecida());
                                this.preencheTabelaMercadoriasInseridas();
                            }
                        }
                    } else if (opc == 2) {

                    }
                }

                cbAlterar.setSelected(false);

                tfDado.setText("");
                tfDado.requestFocusInWindow();

                tfQuant.setText("Insira a quantidade...");
                tfQuant.setForeground(Color.GRAY);

                tfLote.setText("Insira o lote...");
                tfLote.setForeground(Color.GRAY);

                tfPreco.setText("");
                tfPreco.setEnabled(false);

                lblCodigo.setText("");
                lblNome.setText("");
                lblQtdEstoque.setText("");

                mercadoriaSelecionada = null;

                cbOpc.setSelectedIndex(0);

                try {
                    mercadoriasListadas = ControleObjeto.listarTodosMercadoriasEAtivos();
                    this.preencheTabelaPesquisa();
                } catch (RuntimeException e) {
                    JOptionPane.showMessageDialog(null, "Deu ruium: " + e);
                }

                this.calculaTotal();

            }
        }
    }

    private boolean itemJaInserido(ObjetoFornecimento of) {
        for (ObjetoFornecimento objFor : mercadoriasNoFornecimento) {
            if (objFor.getObjeto().getCodigo() == of.getObjeto().getCodigo()) {
                return true;
            }
        }
        return false;
    }

    private void preencheTabelaMercadoriasInseridas() {
        DefaultTableModel dtm = this.criaTabelaMercadoriasInseridas();

        dtm.addColumn("Código");
        dtm.addColumn("Nome");
        dtm.addColumn("Preço de compra");
        dtm.addColumn("Qtde fornecida");
        dtm.addColumn("Sub-total");
        dtm.addColumn("Nova qtde em estoque");

        for (ObjetoFornecimento of : mercadoriasNoFornecimento) {
            dtm.addRow(new Object[]{of.getObjeto().getCodigo(), of.getObjeto().getNome(), of.getPrecoPraticadoCompra(),
                of.getQtdeFornecida(), (of.getPrecoPraticadoCompra() * of.getQtdeFornecida()),
                (of.getObjeto().getQtdeEstoque() + of.getQtdeFornecida())});
        }

        tableMercadoriasInseridas.setModel(dtm);
    }

    private DefaultTableModel criaTabelaMercadoriasInseridas() {
        DefaultTableModel dTable = new DefaultTableModel() {

            Class[] types = new Class[]{
                java.lang.Integer.class, //codigo
                java.lang.String.class, //nome
                java.lang.Float.class, //preço de compra
                java.lang.Float.class, //Qtde Comprada
                java.lang.Float.class, //Sub-total
                java.lang.Float.class //Nova qtde em estoque
            };

            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;

        };
        return dTable;
    }

    private void calculaTotal() {
        float valorTotal = 0;
        for (ObjetoFornecimento of : mercadoriasNoFornecimento) {
            valorTotal += (of.getPrecoPraticadoCompra() * of.getQtdeFornecida());
        }

        lblTotal.setText(valorTotal + "");
    }

    public void pegaFornecimento(Fornecimento f) {
        this.fornecimento = f;
        this.mercadoriasNoFornecimento = f.getObjetosNoFornecimento();

        this.preencheTabelaMercadoriasInseridas();
        this.calculaTotal();
    }
}
