/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Outros;

import Controle.ControleObjeto;
import Controle.ControleSaida;
import Modelo.BEAN.Objeto;
import Modelo.BEAN.ObjetoSaida;
import Modelo.BEAN.Saida;
import java.awt.Color;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilherme
 */
public class FRMSaida extends javax.swing.JFrame {

    private List<Objeto> mercadoriasListadas;
    private Objeto mercadoriaSelecionada;
    private List<ObjetoSaida> mercadoriasNaSaida;
    private Saida s;

    /**
     * Creates new form FRMSaida
     */
    public FRMSaida() {
        initComponents();

        s = new Saida();
        mercadoriaSelecionada = null;
        mercadoriasNaSaida = new ArrayList<>();

        try {
            mercadoriasListadas = ControleObjeto.listarTodosMercadorias();
            this.preencheTabelaPesquisa();
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, "Deu ruium: " + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content os this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbOpc = new javax.swing.JComboBox<>();
        tfDado = new javax.swing.JTextField();
        btnLocalizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePesquisa = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfPreco = new javax.swing.JTextField();
        btnInserirItem = new javax.swing.JButton();
        cbAlterar = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        lblQtdEstoque = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfQuant = new javax.swing.JTextField();
        lblImg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnRemover = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMercadoriasInseridas = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfAcr = new javax.swing.JTextField();
        tfDebt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Saida do Estoque");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Localizar mercadoria por:");

        cbOpc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listar todos", "Código", "Nome", "(A partir) Preço de compra", "(Até)Preço de compra", "Listar apenas ativos", "Listar apenas inativos" }));
        cbOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpcActionPerformed(evt);
            }
        });

        tfDado.setForeground(new java.awt.Color(153, 153, 153));
        tfDado.setText("Insira o dado para pesquisa...");
        tfDado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDadoFocusLost(evt);
            }
        });
        tfDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDadoActionPerformed(evt);
            }
        });
        tfDado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDadoKeyTyped(evt);
            }
        });

        btnLocalizar.setText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(cbOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfDado, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLocalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnLocalizar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Escolha a mercadoria"));

        tablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablePesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePesquisaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePesquisa);

        jLabel6.setText("Código:");

        jLabel13.setText("Nome:");

        jLabel14.setText("Preço de compra:");

        tfPreco.setEnabled(false);
        tfPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPrecoFocusGained(evt);
            }
        });
        tfPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecoActionPerformed(evt);
            }
        });
        tfPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrecoKeyTyped(evt);
            }
        });

        btnInserirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/addProduto.png"))); // NOI18N
        btnInserirItem.setText("Inserir");
        btnInserirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirItemActionPerformed(evt);
            }
        });
        btnInserirItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnInserirItemKeyTyped(evt);
            }
        });

        cbAlterar.setBackground(new java.awt.Color(204, 255, 204));
        cbAlterar.setText("Alterar nesta saída");
        cbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlterarActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade em estoque:");

        jLabel2.setText("Quantidade na saída");

        tfQuant.setForeground(new java.awt.Color(153, 153, 153));
        tfQuant.setText("Insira a quantidade...");
        tfQuant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfQuantFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfQuantFocusLost(evt);
            }
        });
        tfQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantActionPerformed(evt);
            }
        });
        tfQuant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQuantKeyTyped(evt);
            }
        });

        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(10, 10, 10)
                                .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbAlterar)))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInserirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel13))
                            .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(lblQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAlterar))
                        .addGap(20, 20, 20)
                        .addComponent(btnInserirItem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/TiraProduto.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/FinalVenda.png"))); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/logout.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizar)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Mercadorias já selecionadas"));

        tableMercadoriasInseridas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableMercadoriasInseridas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setText("Acréscimo Adicional:");

        jLabel7.setText("Débito adicional:");

        tfAcr.setText("0.00");
        tfAcr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAcrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAcrFocusLost(evt);
            }
        });
        tfAcr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfAcrKeyTyped(evt);
            }
        });

        tfDebt.setText("0.00");
        tfDebt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDebtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDebtFocusLost(evt);
            }
        });
        tfDebt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDebtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfAcr, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfDebt)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(tfAcr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 657, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpcActionPerformed
        if (cbOpc.getSelectedIndex() == 0) {
            try {
                mercadoriasListadas = ControleObjeto.listarTodosMercadorias();
                this.preencheTabelaPesquisa();
                this.verificaTabelaPesquisa();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
            }
        } else if (cbOpc.getSelectedIndex() == 5) {
            try {
                mercadoriasListadas = ControleObjeto.listarTodosMercadoriasEAtivos();
                this.preencheTabelaPesquisa();
                this.verificaTabelaPesquisa();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
            }
        } else if (cbOpc.getSelectedIndex() == 6) {
            try {
                mercadoriasListadas = ControleObjeto.listarTodosMercadoriasEInativos();
                this.preencheTabelaPesquisa();
                this.verificaTabelaPesquisa();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
            }
        }
    }//GEN-LAST:event_cbOpcActionPerformed

    private void tfDadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDadoFocusGained
        if (tfDado.getText().equals("Insira o dado para pesquisa...")) {
            tfDado.setText("");
            tfDado.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfDadoFocusGained

    private void tfDadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDadoFocusLost
        if (tfDado.getText().equals("")) {
            tfDado.setForeground(Color.GRAY);
            tfDado.setText("Insira o dado para pesquisa...");
        }
    }//GEN-LAST:event_tfDadoFocusLost

    private void tfDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDadoActionPerformed
        this.localizar();
    }//GEN-LAST:event_tfDadoActionPerformed

    private void tfDadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDadoKeyTyped

    }//GEN-LAST:event_tfDadoKeyTyped

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        this.localizar();
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void tablePesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePesquisaMouseClicked
        int qnt = tablePesquisa.getSelectedColumnCount();

        if (qnt < 1) {

        } else if (qnt > 1) {

        } else {
            mercadoriaSelecionada = mercadoriasListadas.get(tablePesquisa.getSelectedRow());
            this.preencheDados();
        }
    }//GEN-LAST:event_tablePesquisaMouseClicked

    private void tfPrecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrecoFocusGained
        tfPreco.selectAll();
    }//GEN-LAST:event_tfPrecoFocusGained

    private void tfPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecoActionPerformed
        this.inserirItem();
    }//GEN-LAST:event_tfPrecoActionPerformed

    private void tfPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecoKeyTyped
        String caracteres = "0987654321.,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfPrecoKeyTyped

    private void tfQuantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfQuantFocusGained
        if (tfQuant.getText().equals("Insira a quantidade...")) {
            tfQuant.setText("");
            tfQuant.setForeground(Color.BLACK);
        } else {
            tfQuant.selectAll();
        }
    }//GEN-LAST:event_tfQuantFocusGained

    private void tfQuantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfQuantFocusLost
        if (tfQuant.getText().equals("")) {
            tfQuant.setText("Insira a quantidade...");
            tfQuant.setForeground(Color.GRAY);
        } else {
            String qtde = tfQuant.getText();

            if (qtde.contains(",")) {
                String[] parts = qtde.split(",");
                String part1 = parts[0];
                String part2 = parts[1];
                qtde = part1 + "." + part2;
            }

            if ((mercadoriaSelecionada != null) && (Float.parseFloat(qtde) > mercadoriaSelecionada.getQtdeEstoque())) {
                lblImg.setVisible(true);
                lblImg.setToolTipText("Quantidade excede estoque!");
                URL url = getClass().getResource("/Visao.icon/warning.png");
                ImageIcon icon = new ImageIcon(url);
                lblImg.setIcon(icon);
            } else {
                lblImg.setVisible(false);
            }
        }
    }//GEN-LAST:event_tfQuantFocusLost

    private void tfQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantActionPerformed
        if (cbAlterar.isSelected()) {
            tfPreco.requestFocusInWindow();
        } else {
            this.inserirItem();
        }
    }//GEN-LAST:event_tfQuantActionPerformed

    private void tfQuantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantKeyTyped
        String caracteres = "0987654321.,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfQuantKeyTyped

    private void btnInserirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirItemActionPerformed
        this.inserirItem();
    }//GEN-LAST:event_btnInserirItemActionPerformed

    private void btnInserirItemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInserirItemKeyTyped

    }//GEN-LAST:event_btnInserirItemKeyTyped

    private void cbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlterarActionPerformed
        tfPreco.setEnabled(cbAlterar.isSelected());

        if (mercadoriaSelecionada != null) {
            if (!cbAlterar.isSelected()) {
                tfPreco.setText(mercadoriaSelecionada.getPrecoCompraBase() + "");
            }
        }
    }//GEN-LAST:event_cbAlterarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int qnt = tableMercadoriasInseridas.getSelectedRowCount();

        if (qnt < 1) {
            JOptionPane.showMessageDialog(null, "Selecione um ítem da lista ao lado para remover.");
        } else if (qnt > 1) {
            JOptionPane.showMessageDialog(null, "Apenas um ítem da lista deve ser selecionado por vez.");
        } else {
            ObjetoSaida os = mercadoriasNaSaida.get(tableMercadoriasInseridas.getSelectedRow());
            mercadoriasNaSaida.remove(os);
            this.preencheTabelaMercadoriasInseridas();
            this.calculaTotal();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        if (mercadoriasNaSaida.size() == 0) {
            JOptionPane.showMessageDialog(null, "Insira ao menos um item.");
        } else {
            s.setDataHora(new Date());
            s.setAcrescimoAdicional(Float.parseFloat(tfAcr.getText()));
            s.setDebitoAdicional(Float.parseFloat(tfDebt.getText()));
            s.setObjetos(mercadoriasNaSaida);
            s.setTipoSaida(Saida.TipoSaida.SAIDAMANUAL);
            
            try {
                ControleSaida.insereSaidaEItens(s);
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
            }
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        FRMPrincipal principal = new FRMPrincipal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void tfAcrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAcrKeyTyped
        String caracteres = "0987654321.,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfAcrKeyTyped

    private void tfDebtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDebtKeyTyped
        String caracteres = "0987654321.,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfDebtKeyTyped

    private void tfAcrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAcrFocusGained
        tfAcr.selectAll();
    }//GEN-LAST:event_tfAcrFocusGained

    private void tfDebtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDebtFocusGained
        tfDebt.selectAll();
    }//GEN-LAST:event_tfDebtFocusGained

    private void tfAcrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAcrFocusLost
        try {
            if (tfAcr.getText().equals("")) {
                tfAcr.setText("0.00");
            } else {
                String acr = tfAcr.getText();

                if (acr.contains(",")) {
                    String[] parts = acr.split(",");
                    String part1 = parts[0];
                    String part2 = parts[1];

                    acr = part1 + "." + part2;
                }

                float f = Float.parseFloat(acr);
                tfAcr.setText(acr);
            }
        } catch (NumberFormatException e) {
            tfAcr.setText("0.00");
            JOptionPane.showMessageDialog(null, "Formato inválido!");
        } finally {
            this.calculaTotal();
        }
    }//GEN-LAST:event_tfAcrFocusLost

    private void tfDebtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDebtFocusLost
        try {
            if (tfDebt.getText().equals("")) {
                tfDebt.setText("0.00");
            } else {
                String debt = tfDebt.getText();

                if (debt.contains(",")) {
                    String[] parts = debt.split(",");
                    String part1 = parts[0];
                    String part2 = parts[1];

                    debt = part1 + "." + part2;
                }

                float f = Float.parseFloat(debt);
                tfDebt.setText(debt);
            }
        } catch (NumberFormatException e) {
            tfDebt.setText("0.00");
            JOptionPane.showMessageDialog(null, "Formato inválido!");
        } finally {
            this.calculaTotal();
        }
    }//GEN-LAST:event_tfDebtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" debt=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMSaida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnInserirItem;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox cbAlterar;
    private javax.swing.JComboBox<String> cbOpc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQtdEstoque;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tableMercadoriasInseridas;
    private javax.swing.JTable tablePesquisa;
    private javax.swing.JTextField tfAcr;
    private javax.swing.JTextField tfDado;
    private javax.swing.JTextField tfDebt;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfQuant;
    // End of variables declaration//GEN-END:variables

    private void preencheTabelaPesquisa() {

        DefaultTableModel dtm = this.criaTabelaPesquisa();

        dtm.addColumn("Código");
        dtm.addColumn("Nome");
        dtm.addColumn("Preço de compra");
        dtm.addColumn("Qtde em estoque");

        for (Objeto ml : mercadoriasListadas) {
            dtm.addRow(new Object[]{ml.getCodigo(), ml.getNome(), ml.getPrecoCompraBase(), ml.getQtdeEstoque()});
        }

        tablePesquisa.setModel(dtm);

    }

    private DefaultTableModel criaTabelaPesquisa() {
        DefaultTableModel dTable = new DefaultTableModel() {
            //Define o tipo dos campos (coluna) na mesma ordem que as colunas foram criadas
            Class[] types = new Class[]{
                java.lang.Integer.class, //codigo
                java.lang.String.class, //nome
                java.lang.Float.class, //preço de compra
                java.lang.Float.class //Qtde em estoque
            };

            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;

        };
        
    return dTable;
    }

    private void verificaTabelaPesquisa() {
        if (tablePesquisa.getRowCount() == 1) {
            mercadoriaSelecionada = mercadoriasListadas.get(0);
            this.preencheDados();
        }
    }

    private void localizar() {
        if ((tfDado.getText().equals("")) || (tfDado.getText().equals("Insira o dado para pesquisa..."))) {
            JOptionPane.showMessageDialog(null, "Insira algum dado para pesquisa.");
        } else {
            if (cbOpc.getSelectedIndex() == 1) {
                try {
                    mercadoriasListadas = ControleObjeto.listarMercadoriaPorCodigo(Integer.parseInt(tfDado.getText()));
                    this.preencheTabelaPesquisa();
                    this.verificaTabelaPesquisa();
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Atenção: para pesquisa por código, insira apenas números.");
                } catch (RuntimeException e) {
                    JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
                }

            } else if (cbOpc.getSelectedIndex() == 2) {
                try {
                    mercadoriasListadas = ControleObjeto.listarMercadoriaPorNome(tfDado.getText());
                    this.preencheTabelaPesquisa();
                    this.verificaTabelaPesquisa();
                } catch (RuntimeException e) {
                    JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
                }
            } else if (cbOpc.getSelectedIndex() == 3) {
                String texto = tfDado.getText();

                if (texto.contains(",")) {
                    String partes[] = texto.split(",");
                    String parte1 = partes[0];
                    String parte2 = partes[1];
                    texto = parte1 + "." + parte2;
                }
                try {
                    mercadoriasListadas = ControleObjeto.listarMercadoriaPorValorCompraMenor(Float.parseFloat(texto));
                    this.preencheTabelaPesquisa();
                    this.verificaTabelaPesquisa();
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Atenção: para pesquisa por valores, insira apenas números.");
                } catch (RuntimeException e) {
                    JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
                }

            } else if (cbOpc.getSelectedIndex() == 4) {
                String texto = tfDado.getText();

                if (texto.contains(",")) {
                    String partes[] = texto.split(",");
                    String parte1 = partes[0];
                    String parte2 = partes[1];
                    texto = parte1 + "." + parte2;
                }
                try {
                    mercadoriasListadas = ControleObjeto.listarMercadoriaPorValorCompraMaior(Float.parseFloat(texto));
                    this.preencheTabelaPesquisa();
                    this.verificaTabelaPesquisa();
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Atenção: para pesquisa por valores, insira apenas números.");
                } catch (RuntimeException e) {
                    JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
                }
            }
        }
    }

    private void preencheDados() {
        lblCodigo.setText(mercadoriaSelecionada.getCodigo() + "");
        lblNome.setText(mercadoriaSelecionada.getNome());
        lblQtdEstoque.setText(mercadoriaSelecionada.getQtdeEstoque() + "");
        tfPreco.setText(mercadoriaSelecionada.getPrecoCompraBase() + "");
        tfQuant.setForeground(Color.BLACK);
        tfQuant.setText("1");
        tfQuant.requestFocusInWindow();
    }

    private void inserirItem() {
        if (mercadoriaSelecionada == null) {
            JOptionPane.showMessageDialog(null, "Selecione uma mercadoria ao lado.");
        } else {
            if (tfPreco.getText().equals("") || (tfQuant.getText().equals("Insira a quantidade...")) || (tfQuant.getText().equals(""))) {
                JOptionPane.showMessageDialog(null, "Todos os dados devem ser preenchidos");
            } else {

                ObjetoSaida os = new ObjetoSaida();

                os.setObjeto(mercadoriaSelecionada);
                os.setSaida(s);

                String qtde = tfQuant.getText();

                if (qtde.contains(",")) {
                    String[] parts = qtde.split(",");
                    String part1 = parts[0];
                    String part2 = parts[1];
                    qtde = part1 + "." + part2;
                }

                os.setQtdeRetirada(Float.parseFloat(qtde));

                String precoPraticado = tfPreco.getText();

                if (precoPraticado.contains(",")) {
                    String[] parts = precoPraticado.split(",");
                    String part1 = parts[0];
                    String part2 = parts[1];
                    precoPraticado = part1 + "." + part2;
                }

                os.setPrecoCompraNaSaida(Float.parseFloat(precoPraticado));

                int limpaDados = 0;

                if (!this.itemJaInserido(os)) {
                    mercadoriasNaSaida.add(os);
                    this.preencheTabelaMercadoriasInseridas();
                } else {
                    Object[] opcoes = {"Substituir", "Acrescentar quantidade", "Cancelar"};
                    int opc = JOptionPane.showOptionDialog(null, "Mercadoria já inserida! O que deseja fazer?",
                            "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opcoes, opcoes[0]);

                    if (opc == 0) {
                        for (ObjetoSaida objSai : mercadoriasNaSaida) {
                            if (objSai.getObjeto().getCodigo() == os.getObjeto().getCodigo()) {
                                objSai.setPrecoCompraNaSaida(os.getPrecoCompraNaSaida());
                                objSai.setQtdeRetirada(os.getQtdeRetirada());
                                this.preencheTabelaMercadoriasInseridas();
                            }
                        }
                    } else if (opc == 1) {
                        for (ObjetoSaida objSai : mercadoriasNaSaida) {
                            if (objSai.getObjeto().getCodigo() == os.getObjeto().getCodigo()) {
                                objSai.setQtdeRetirada(objSai.getQtdeRetirada() + os.getQtdeRetirada());
                                this.preencheTabelaMercadoriasInseridas();
                            }
                        }
                    } else if (opc == 2) {
                        limpaDados = 1;
                    }
                }

                if (limpaDados == 0) {

                    cbAlterar.setSelected(false);

                    tfDado.setText("");
                    tfDado.requestFocusInWindow();

                    tfQuant.setText("Insira a quantidade...");
                    tfQuant.setForeground(Color.GRAY);

                    tfPreco.setText("");
                    tfPreco.setEnabled(false);

                    lblImg.setVisible(false);
                    lblCodigo.setText("");
                    lblNome.setText("");
                    lblQtdEstoque.setText("");

                    mercadoriaSelecionada = null;

                    cbOpc.setSelectedIndex(0);

                    try {
                        mercadoriasListadas = ControleObjeto.listarTodosMercadorias();
                        this.preencheTabelaPesquisa();
                    } catch (RuntimeException e) {
                        JOptionPane.showMessageDialog(null, "Deu ruium: " + e);
                    }

                    this.calculaTotal();
                }

            }
        }
    }

    private boolean itemJaInserido(ObjetoSaida os) {
        for (ObjetoSaida objSai : mercadoriasNaSaida) {
            if (objSai.getObjeto().getCodigo() == os.getObjeto().getCodigo()) {
                return true;
            }
        }
        return false;
    }

    private void preencheTabelaMercadoriasInseridas() {
        DefaultTableModel dtm = this.criaTabelaMercadoriasInseridas();

        dtm.addColumn("Código");
        dtm.addColumn("Nome");
        dtm.addColumn("Preço de compra");
        dtm.addColumn("Qtde retirada");
        dtm.addColumn("Sub-total");
        dtm.addColumn("Nova qtde em estoque");

        for (ObjetoSaida os : mercadoriasNaSaida) {
            dtm.addRow(new Object[]{os.getObjeto().getCodigo(), os.getObjeto().getNome(), os.getPrecoCompraNaSaida(),
                os.getQtdeRetirada(), (os.getPrecoCompraNaSaida() * os.getQtdeRetirada()),
                (os.getObjeto().getQtdeEstoque() - os.getQtdeRetirada())});
        }

        tableMercadoriasInseridas.setModel(dtm);
    }

    private DefaultTableModel criaTabelaMercadoriasInseridas() {
        DefaultTableModel dTable = new DefaultTableModel() {

            Class[] types = new Class[]{
                java.lang.Integer.class, //codigo
                java.lang.String.class, //nome
                java.lang.Float.class, //preço de compra
                java.lang.Float.class, //Qtde Comprada
                java.lang.Float.class, //Sub-total
                java.lang.Float.class //Nova qtde em estoque
            };

            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;

        };
        return dTable;
    }

    private void calculaTotal() {
        float valorTotal = 0;
        for (ObjetoSaida os : mercadoriasNaSaida) {
            valorTotal += (os.getPrecoCompraNaSaida() * os.getQtdeRetirada());
        }

        String debt = tfDebt.getText();

        if (debt.contains(",")) {
            String[] parts = debt.split(",");
            String part1 = parts[0];
            String part2 = parts[1];

            debt = part1 + "." + part2;
        }

        String acr = tfAcr.getText();

        if (acr.contains(",")) {
            String[] parts = acr.split(",");
            String part1 = parts[0];
            String part2 = parts[1];

            acr = part1 + "." + part2;
        }

        valorTotal -= Float.parseFloat(debt);
        valorTotal += Float.parseFloat(acr);

        lblTotal.setText(valorTotal + "");
    }

}
