/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Edicao;

import Controle.ControleObjeto;
import Controle.ControleSubGrupo;
import Modelo.BEAN.Objeto;
import Modelo.BEAN.SubGrupo;
import Visao.Gerenciamento.FRMObjeto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class FRMEditarObjeto extends javax.swing.JFrame {

    Objeto objetobean = new Objeto();
    List<SubGrupo> g;

    /**
     * Creates new form CadastrarFornecedor
     */
    public FRMEditarObjeto() {
        initComponents();

        g = ControleSubGrupo.listarTodos();

        this.preencheComboBoxTipo();

        lblPC.setVisible(false);
        tfPCompra.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbSubGrupo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbUn = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDesc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        rbProduto = new javax.swing.JRadioButton();
        rbMercadoria = new javax.swing.JRadioButton();
        tfPVenda = new javax.swing.JTextField();
        lblPV = new javax.swing.JLabel();
        lblPC = new javax.swing.JLabel();
        tfPCompra = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnReativar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar Objeto");

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nome:");

        jLabel4.setText("Sub-grupo:");

        cbSubGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSubGrupoActionPerformed(evt);
            }
        });

        jLabel11.setText("Unidade:");

        cbUn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidade", "Kilograma", "Grama", "Litro", "Mililitro" }));

        jLabel14.setText("Descrição:");

        taDesc.setColumns(20);
        taDesc.setRows(5);
        jScrollPane1.setViewportView(taDesc);

        jLabel2.setText("Selecione o tipo:");

        rbProduto.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(rbProduto);
        rbProduto.setSelected(true);
        rbProduto.setText("Produto");
        rbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbProdutoActionPerformed(evt);
            }
        });

        rbMercadoria.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(rbMercadoria);
        rbMercadoria.setText("Mercadoria");
        rbMercadoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMercadoriaActionPerformed(evt);
            }
        });

        tfPVenda.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfPVendaCaretUpdate(evt);
            }
        });
        tfPVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPVendaKeyTyped(evt);
            }
        });

        lblPV.setText("Preço de venda:");

        lblPC.setText("Preço de compra:");

        tfPCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPCompraKeyTyped(evt);
            }
        });

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/prodEditar.png"))); // NOI18N
        btnCadastrar.setText("Editar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/logout.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnReativar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/bringback.png"))); // NOI18N
        btnReativar.setText("Reativar");
        btnReativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReativarActionPerformed(evt);
            }
        });

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao.icon/del.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(tfNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReativar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbMercadoria)
                                .addGap(18, 18, 18)
                                .addComponent(lblPC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfPCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbUn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSubGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4)
                    .addComponent(cbSubGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbProduto)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMercadoria)
                    .addComponent(lblPC)
                    .addComponent(tfPCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVoltar)
                    .addComponent(btnReativar)
                    .addComponent(btnDeletar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPVendaKeyTyped
        String caracteres = "0987654321.,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfPVendaKeyTyped

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if ((tfNome.getText().equals("")) || (tfPVenda.getText().equals("")) || ((rbMercadoria.isSelected()) && (tfPCompra.getText().equals("")))) {
            JOptionPane.showMessageDialog(null, "Com exceção do campo de descrição, todos os campos devem estar preenchidos");
        } else {

            Objeto objeto = new Objeto();

            objeto.setCodigo(objetobean.getCodigo());
            objeto.setSituacaoObj(objetobean.getSituacaoObj());
            objeto.setQtdeEstoque(objetobean.getQtdeEstoque());

            objeto.setNome(tfNome.getText());
            objeto.setDescricao(taDesc.getText());

            String precoVenda = tfPVenda.getText();

            if (precoVenda.contains(",")) {
                String[] parts = precoVenda.split(",");
                String part1 = parts[0];
                String part2 = parts[1];
                precoVenda = part1 + "." + part2;
            }
            objeto.setPrecoVendaBase(Float.parseFloat(precoVenda));

            if (rbProduto.isSelected()) {
                objeto.setTipoObj(Objeto.TipoObjeto.PRODUTO);
            } else if (rbMercadoria.isSelected()) {
                objeto.setTipoObj(Objeto.TipoObjeto.MERCADORIA);

                String precoCompra = tfPCompra.getText();

                if (precoCompra.contains(",")) {
                    String[] parts = precoCompra.split(",");
                    String part1 = parts[0];
                    String part2 = parts[1];
                    precoCompra = part1 + "." + part2;
                }
                objeto.setPrecoCompraBase(Float.parseFloat(precoCompra));

            }

            if (cbUn.getSelectedIndex() == 0) {
                objeto.setUnidade(Objeto.Unidade.UNIDADE);
            } else if (cbUn.getSelectedIndex() == 1) {
                objeto.setUnidade(Objeto.Unidade.KILOGRAMA);
            } else if (cbUn.getSelectedIndex() == 2) {
                objeto.setUnidade(Objeto.Unidade.GRAMA);
            } else if (cbUn.getSelectedIndex() == 3) {
                objeto.setUnidade(Objeto.Unidade.LITRO);
            } else if (cbUn.getSelectedIndex() == 4) {
                objeto.setUnidade(Objeto.Unidade.MILILITRO);
            }

            objeto.setSubGrupo(g.get(cbSubGrupo.getSelectedIndex()));

            if (objeto.equals(objetobean)) {
                JOptionPane.showMessageDialog(null, "Faça alguma modificação primeiro.");
            } else {
                try {
                    ControleObjeto.editaObjeto(objeto);

                    JOptionPane.showMessageDialog(null, "Objeto editado com sucesso.");

                    this.mudaFrame();
                } catch (RuntimeException e) {
                    JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
                    throw new RuntimeException(e);
                }
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.mudaFrame();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbSubGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSubGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSubGrupoActionPerformed

    private void tfPVendaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfPVendaCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPVendaCaretUpdate

    private void rbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbProdutoActionPerformed
        lblPC.setVisible(false);
        tfPCompra.setVisible(false);
    }//GEN-LAST:event_rbProdutoActionPerformed

    private void rbMercadoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMercadoriaActionPerformed
        lblPC.setVisible(true);
        tfPCompra.setVisible(true);
    }//GEN-LAST:event_rbMercadoriaActionPerformed

    private void tfPCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPCompraKeyTyped
        String caracteres = "0987654321.,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfPCompraKeyTyped

    private void btnReativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReativarActionPerformed
        if (objetobean.getSituacaoObj().equals(Objeto.SituacaoObj.ATIVO)) {
            JOptionPane.showMessageDialog(null, "Este objeto não está inativado.");
        } else {
            try {
                ControleObjeto.reativaObjeto(objetobean);
                JOptionPane.showMessageDialog(null, "Objeto reativado com sucesso!");
                this.mudaFrame();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(null, "Deu ruim: " + e);
            }
        }
    }//GEN-LAST:event_btnReativarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        int opc = JOptionPane.showConfirmDialog(null, "Deseja realmente deletar o objeto " + objetobean.getNome() + "?"
                + " Todas as vendas, saidas e fornecimentos em que esse objeto participou também serão apagados, por isso, é ALTAMENTE RECOMENDADO NÃO"
                + " apagar o objeto, mas apenas inativá-lo.");

        if (opc == 0) {
            try {
                ControleObjeto.deletaObjeto(objetobean);
                JOptionPane.showMessageDialog(null, "Objeto deletado com sucesso!");
                this.mudaFrame();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(null, "Deu Ruim: " + e);
            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMEditarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMEditarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMEditarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMEditarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMEditarObjeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnReativar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbSubGrupo;
    private javax.swing.JComboBox<String> cbUn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblPV;
    private javax.swing.JRadioButton rbMercadoria;
    private javax.swing.JRadioButton rbProduto;
    private javax.swing.JTextArea taDesc;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPCompra;
    private javax.swing.JTextField tfPVenda;
    // End of variables declaration//GEN-END:variables

    private void preencheComboBoxTipo() {

        for (SubGrupo sg : g) {
            cbSubGrupo.addItem(sg.getNome());
        }
    }

    public void pegaObjeto(Objeto obj) {
        objetobean = obj;
        this.preencheDados();
    }

    private void preencheDados() {
        tfNome.setText(objetobean.getNome());
        tfPVenda.setText(Float.toString(objetobean.getPrecoVendaBase()));
        taDesc.setText(objetobean.getDescricao());
        cbSubGrupo.setSelectedItem(objetobean.getSubGrupo().getNome());

        int index = 0;
        for (SubGrupo sg : g) {
            if (sg.getCodigo() == objetobean.getSubGrupo().getCodigo()) {
                cbSubGrupo.setSelectedIndex(index);
            }
            index++;
        }

        if (objetobean.getTipoObj().equals(Objeto.TipoObjeto.PRODUTO)) {
            rbProduto.setSelected(true);
        } else if (objetobean.getTipoObj().equals(Objeto.TipoObjeto.MERCADORIA)) {
            lblPC.setVisible(true);
            tfPCompra.setVisible(true);
            rbMercadoria.setSelected(true);
            tfPCompra.setText(Float.toString(objetobean.getPrecoCompraBase()));
        }

        if (objetobean.getUnidade().equals(Objeto.Unidade.UNIDADE)) {
            cbUn.setSelectedIndex(0);
        } else if (objetobean.getUnidade().equals(Objeto.Unidade.KILOGRAMA)) {
            cbUn.setSelectedIndex(1);
        } else if (objetobean.getUnidade().equals(Objeto.Unidade.GRAMA)) {
            cbUn.setSelectedIndex(2);
        } else if (objetobean.getUnidade().equals(Objeto.Unidade.LITRO)) {
            cbUn.setSelectedIndex(3);
        } else if (objetobean.getUnidade().equals(Objeto.Unidade.MILILITRO)) {
            cbUn.setSelectedIndex(4);
        }
    }

    private void mudaFrame() {
        FRMObjeto fO = new FRMObjeto();

        fO.setVisible(true);

        this.dispose();
    }
}
